export const CART_ACTION_TYPES = {
  SET_CART_OPEN: "cartr/SET_CART_OPEN",
  ADD_ITEM_TO_CART: "cartr/ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "cartr/REMOVE_ITEM_FROM_CART",
  DISCARD_ITEM: "cartr/DISCARD_ITEM",
};
